// useSupabase Hook - Auto-generated by Backend Service
// ALWAYS use this hook for Supabase operations to ensure proper authentication
// This hook returns the single shared Supabase client and a retry helper for
// authenticated mutations that may encounter an expired JWT.

import { useCallback } from 'react';
import { useAuth } from './auth-context';
import { runWithFreshSession, supabase } from './supabase';

export function useSupabase() {
  const { session, user, signOut } = useAuth();

  const withAuthRetry = useCallback((operation) => (
    runWithFreshSession(operation, {
      onSessionExpired: async () => {
        await signOut?.();
        if (typeof window !== 'undefined') {
          const redirect = `${window.location.pathname}${window.location.search}`;
          window.location.assign(`/auth?redirect=${encodeURIComponent(redirect)}&reason=session_expired`);
        }
      },
    })
  ), [signOut]);

  return {
    supabase,
    isAuthenticated: !!session,
    user,
    withAuthRetry,
  };
}
