export const DEMO_USERS = [
  {
    id: 'u1',
    name: 'Maria Borg',
    username: 'maria.borg',
    email: 'maria@example.com',
    location: 'Sliema',
    avatar: null,
    rating: 4.8,
    reviewCount: 23,
    joined: '2024-03-15',
    listings: 12,
    sold: 8,
  },
  {
    id: 'u2',
    name: 'Gozo Vintage',
    username: 'gozo.vintage',
    email: 'gozo@example.com',
    location: 'Gozo',
    avatar: null,
    rating: 4.9,
    reviewCount: 47,
    joined: '2023-11-01',
    listings: 34,
    sold: 28,
  },
  {
    id: 'u3',
    name: 'Sib Admin',
    username: 'sibadmin',
    email: 'info@sibmalta.com',
    location: 'Valletta',
    avatar: null,
    rating: 0,
    reviewCount: 0,
    joined: '2023-01-01',
    listings: 0,
    sold: 0,
    isAdmin: true,
  },
]

export const DEMO_LISTINGS = [
  {
    id: 'l1',
    title: 'Zara Floral Midi Dress',
    price: 18,
    category: 'dresses',
    sellCategory: 'women',
    condition: 'like_new',
    size: 'M',
    description: 'Beautiful floral midi dress from Zara. Worn once for a wedding. Perfect condition, no marks or stains.',
    location: 'Sliema',
    sellerId: 'u1',
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop'],
    createdAt: '2025-03-20T10:30:00Z',
    liked: false,
    views: 45,
  },
  {
    id: 'l2',
    title: 'Levi\'s 501 Original Jeans',
    price: 25,
    category: 'jeans',
    sellCategory: 'men',
    condition: 'very_good',
    size: 'L',
    description: 'Classic Levi\'s 501 jeans in great condition. Slight fading gives them a nice vintage look. Size 32/32.',
    location: 'Valletta',
    sellerId: 'u2',
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=800&fit=crop'],
    createdAt: '2025-03-19T14:00:00Z',
    liked: false,
    views: 67,
  },
  {
    id: 'l3',
    title: 'Nike Air Max 90 Sneakers',
    price: 45,
    category: 'shoes',
    sellCategory: 'shoes',
    condition: 'good',
    size: '42',
    description: 'Nike Air Max 90 in white/grey colourway. Some wear on the sole but upper is clean. UK 8 / EU 42.',
    location: 'Birkirkara',
    sellerId: 'u1',
    images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=800&fit=crop'],
    createdAt: '2025-03-18T09:15:00Z',
    liked: false,
    views: 89,
  },
  {
    id: 'l4',
    title: 'Vintage Denim Jacket',
    price: 30,
    category: 'coats',
    sellCategory: 'vintage',
    condition: 'very_good',
    size: 'M',
    description: 'Beautiful vintage denim jacket from the 90s. Authentic worn-in look. Great for layering year-round in Malta.',
    location: 'Gozo',
    sellerId: 'u2',
    images: ['https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&h=800&fit=crop'],
    createdAt: '2025-03-17T16:45:00Z',
    liked: false,
    views: 112,
  },
  {
    id: 'l5',
    title: 'H&M Oversized Hoodie',
    price: 12,
    category: 'hoodies',
    sellCategory: 'women',
    condition: 'good',
    size: 'S',
    description: 'Cozy oversized hoodie in dusty pink. Some light pilling but still in great shape. Very comfy for autumn.',
    location: 'Msida',
    sellerId: 'u1',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=800&fit=crop'],
    createdAt: '2025-03-16T11:00:00Z',
    liked: false,
    views: 34,
  },
  {
    id: 'l6',
    title: 'Ray-Ban Wayfarer Sunglasses',
    price: 55,
    category: 'accessories',
    sellCategory: 'accessories',
    condition: 'like_new',
    size: null,
    description: 'Authentic Ray-Ban Wayfarer sunglasses in classic black. Comes with case and cloth. Barely used.',
    location: 'St Julian\'s',
    sellerId: 'u2',
    images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=800&fit=crop'],
    createdAt: '2025-03-15T08:30:00Z',
    liked: false,
    views: 156,
  },
  {
    id: 'l7',
    title: 'Adidas Track Pants',
    price: 15,
    category: 'activewear',
    sellCategory: 'men',
    condition: 'good',
    size: 'L',
    description: 'Adidas classic track pants with the three stripes. Black with white stripes. Elastic waist, very comfortable.',
    location: 'Mosta',
    sellerId: 'u1',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=800&fit=crop'],
    createdAt: '2025-03-14T13:20:00Z',
    liked: false,
    views: 42,
  },
  {
    id: 'l8',
    title: 'COS Linen Shirt',
    price: 22,
    category: 'shirts',
    sellCategory: 'women',
    condition: 'new_with_tags',
    size: 'S',
    description: 'Brand new COS linen shirt in sage green. Never worn, tags still on. Perfect for Maltese summers.',
    location: 'Naxxar',
    sellerId: 'u2',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=800&fit=crop'],
    createdAt: '2025-03-13T15:50:00Z',
    liked: false,
    views: 78,
  },
  {
    id: 'l9',
    title: 'Kids Gap Denim Overalls',
    price: 10,
    category: 'jeans',
    sellCategory: 'kids',
    condition: 'very_good',
    size: '3-4Y',
    description: 'Adorable Gap denim overalls for toddlers. Age 3-4. Minor wash fade, otherwise perfect. Great for everyday wear.',
    location: 'Rabat',
    sellerId: 'u1',
    images: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&h=800&fit=crop'],
    createdAt: '2025-03-12T10:10:00Z',
    liked: false,
    views: 29,
  },
  {
    id: 'l10',
    title: 'Mango Wool Blend Coat',
    price: 40,
    category: 'coats',
    sellCategory: 'women',
    condition: 'very_good',
    size: 'M',
    description: 'Elegant Mango wool blend coat in camel. Mid-length. A few winter seasons of use but still looks premium.',
    location: 'Attard',
    sellerId: 'u2',
    images: ['https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=600&h=800&fit=crop'],
    createdAt: '2025-03-11T17:30:00Z',
    liked: false,
    views: 93,
  },
]
